name: Deployment

on:
  release:
    types: [published]

jobs:
  deploy-to-dev:
    runs-on: ubuntu-latest
    environment:
      name: delius-core-dev
      url: https://ndelius.dev.probation.service.justice.gov.uk/
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        uses: ./.github/actions/deploy
        with:
          environment: delius-core-dev
          version: "${{ github.event.release.name }}"
          github_token: "${{ secrets.EXT_GITHUB_TOKEN }}"

  deploy-to-sandpit:
    runs-on: ubuntu-latest
    environment:
      name: delius-core-sandpit
      url: https://ndelius.sandpit.probation.service.justice.gov.uk/
    steps:
      - name: deploy
        run: echo "Deploying..."

  deploy-to-mis-dev:
    runs-on: ubuntu-latest
    environment:
      name: mis-dev
      url: https://ndelius.mis-dev.probation.service.justice.gov.uk/
    steps:
      - name: deploy
        run: echo "Deploying..."

  run-smoke-tests:
    runs-on: ubuntu-latest
    needs: [deploy-to-dev, deploy-to-sandpit, deploy-to-mis-dev]
    steps:
      - name: test
        run: echo "Testing..."

  deploy-to-test:
    runs-on: ubuntu-latest
    needs: [run-smoke-tests]
    environment:
      name: test
      url: https://ndelius.test.probation.service.justice.gov.uk/
    steps:
      - name: deploy
        run: echo "Deploying..."

  deploy-to-stage:
    runs-on: ubuntu-latest
    needs: [run-smoke-tests]
    environment:
      name: stage
      url: https://ndelius.stage.probation.service.justice.gov.uk/
    steps:
      - name: deploy
        run: echo "Deploying..."

  run-serenity-tests:
    runs-on: ubuntu-latest
    needs: [deploy-to-test]
    steps:
      - name: test
        run: echo "Running tests..."

  run-performance-tests:
    runs-on: ubuntu-latest
    needs: [deploy-to-stage]
    steps:
      - name: test
        run: echo "Running tests..."

  deploy-to-pre-prod:
    runs-on: ubuntu-latest
    needs: [run-serenity-tests, run-performance-tests]
    environment:
      name: pre-prod
      url: https://ndelius.pre-prod.delius.probation.hmpps.dsd.io/
    steps:
      - name: deploy
        run: echo "Deploying..."

  deploy-to-training:
    runs-on: ubuntu-latest
    needs: [run-serenity-tests, run-performance-tests]
    environment:
      name: training
      url: https://ndelius.training.probation.service.justice.gov.uk/
    steps:
      - name: deploy
        run: echo "Deploying..."
