name: Pipeline

on:
  push

jobs:
  generate-release-note:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt install pdftohtml
          brew install pandoc
      - name: PDF to HTML
        run: pdftohtml -enc UTF-8 -noframes 'release-notes/Delius Service Team ND 5.4.13.1 Release Notes.pdf' release_notes.html
      - name: HTML to Markdown
        run: pandoc --ascii --from html --to markdown release_notes.html | tail -n+5 | sed -E 's/^\*\*/\n\*\*/' | sed -E 's/(.*)\\/\1/' > release_notes.md
      - name: Update GitHub release
        run: gh release edit 'v5.4.13.1' --notes-file release_notes.md
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
