name: Pipeline

on:
  release:
    types: [published]

jobs:

  delius-core-dev:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: delius-core-dev
      environment_url: https://ndelius.dev.probation.service.justice.gov.uk/
      version: ${{ github.event.release.name }}
    secrets: inherit

#  delius-mis-dev: # TODO awaiting confirmation we can auto-deploy to delius-mis-dev
#    uses: ./.github/workflows/deploy.yml
#    with:
#      environment: delius-mis-dev
#      environment_url: https://ndelius.mis-dev.probation.service.justice.gov.uk/
#      version: ${{ github.event.release.name }}
#    secrets: inherit

  test:
    uses: ./.github/workflows/deploy.yml
    needs: [delius-core-dev]
    with:
      environment: delius-test
      environment_url: https://ndelius.test.probation.service.justice.gov.uk/
      version: ${{ github.event.release.name }}
    secrets: inherit

  serenity-tests: # TODO need to move the serenity tests into the delius-pipelines framework for this to work
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_FOR_SERENITY_TESTS }}
          role-skip-session-tagging: true
          role-duration-seconds: 3600
          mask-aws-account-id: false
      - name: Run tests
        uses: marcus-bcl/aws-codebuild-run-build@4d318a89c4d0e91ba639c9220abd258d487efcce
        with:
          project-name: del-test-delius-serenity-tests-build
          disable-source-override: true

  stage:
    uses: ./.github/workflows/deploy.yml
    needs: [delius-core-dev]
    with:
      environment: delius-stage
      environment_url: https://ndelius.stage.probation.service.justice.gov.uk/
      version: ${{ github.event.release.name }}
    secrets: inherit

  performance-tests:
    runs-on: ubuntu-latest
    needs: [stage]
    steps:
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_FOR_PERFORMANCE_TESTS }}
          role-skip-session-tagging: true
      - name: Run tests
        uses: marcus-bcl/aws-codebuild-run-build@4d318a89c4d0e91ba639c9220abd258d487efcce
        with:
          project-name: del-stage-delius-performance-tests-build
          disable-source-override: true
          env-vars-for-codbuild: CONCURRENT_USERS
        env:
          CONCURRENT_USERS: 160

  pre-prod:
    uses: ./.github/workflows/deploy.yml
    needs: [serenity-tests, performance-tests]
    with:
      environment: delius-pre-prod
      environment_url: https://ndelius.pre-prod.delius.probation.hmpps.dsd.io/
      version: ${{ github.event.release.name }}
    secrets: inherit

  training:
    uses: ./.github/workflows/deploy.yml
    needs: [serenity-tests, performance-tests]
    with:
      environment: delius-training
      environment_url: https://ndelius.training.probation.service.justice.gov.uk/
      version: ${{ github.event.release.name }}
    secrets: inherit

  complete:
    runs-on: ubuntu-latest
    needs: [pre-prod, training]
    steps:
      - run: echo Pipeline complete!
