name: Pipeline

on:
  push:

jobs:
  generate-release-note:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: brew install pdftohtml pandoc
      - name: PDF to HTML
        run: pdftohtml -enc UTF-8 -noframes 'release-notes/Delius Service Team ND ${{ github.event.release.name }} Release Notes.pdf' release_notes.html
      - name: HTML to Markdown
        run: pandoc --ascii --from html --to markdown release_notes.html | tail -n+3 > release_notes.md
      - name: Update GitHub release
        run: gh release edit v${{ github.event.release.name }} --notes-file release_notes.md

